"""Verbalisation templates for FFLO knowledge-graph triplets.

Converts a (subject, subject_type, predicate, object, object_type) tuple
into a natural-language sentence suitable as an NLI hypothesis.

All tables are plain Python dicts — add new relations or entity types by
adding one line to the appropriate dict.  Unknown types/relations fall
back to a generic template.

Labels are resolved via ``resolve_label()``, which takes an entity name,
entity type, and an optional ``entity_labels`` lookup (populated by
``synthetic_ids.py`` for structural nodes that need descriptive labels).
"""

# ---------------------------------------------------------------------------
# Type → readable phrase
# ---------------------------------------------------------------------------

TYPE_PHRASES: dict[str, str] = {
    "Food": "",
    "Ingredient": "",
    "ChemicalIngredient": "",
    "Adulterant": "",
    "SyntheticAdulterant": "",
    "NaturalAdulterant": "",
    "ContaminantAdulterant": "",
    "FoodAdditive": "",
    "FoodCategory": "the food category",
    "FoodBusinessOperator": "the food business operator",
    "AdulterationAct": "the adulteration act",
    "AdulterationMethod": "the adulteration method",
    "FraudType": "the fraud type",
    "IntentionalityLevel": "the intentionality level",
    "AdditiveFunction": "the additive function",
    "Preservative": "the preservative",
    "Antioxidant": "the antioxidant",
    "Emulsifier": "the emulsifier",
    "Stabilizer": "the stabilizer",
    "AcidityRegulator": "the acidity regulator",
    "FlourTreatmentAgent": "the flour treatment agent",
    "Sequestrant": "the sequestrant",
    "HumectantAdditive": "the humectant",
    "Colourant": "the colourant",
    "SweeteningAgent": "the sweetening agent",
    "SupplyChainStep": "the supply chain step",
    "Production": "the production stage",
    "Processing": "the processing stage",
    "Storage": "the storage stage",
    "Distribution": "the distribution stage",
    "Retail": "the retail stage",
    "Import": "the import stage",
    "SpreadEvent": "the spread event",
    "TransformationEvent": "the transformation event",
    "GeographicRegion": "the geographic region",
    "Sample": "the sample",
    "Analysis": "the analysis",
    "AnalysisResult": "the analysis result",
    "Measurement": "the measurement",
    "UnitOfMeasure": "the unit",
    "Laboratory": "the laboratory",
    "Location": "the location",
    "Property": "the property",
    "IncidentFinding": "the incident finding",
    "LabConfirmed": "the lab-confirmed finding",
    "FieldDetected": "the field-detected finding",
    "SurveyAggregated": "the survey-aggregated finding",
    "RecallTriggered": "the recall-triggered finding",
    "EvidenceSource": "the evidence source",
    "DetectionMethod": "the detection method",
    "LaboratoryTest": "the laboratory test",
    "FieldTest": "the field test",
    "SensoryTest": "the sensory test",
    "DetectionIndicator": "the detection indicator",
    "DetectionKit": "the detection kit",
    "FoodStandard": "the food standard",
    "RegulatoryDocument": "the regulatory document",
    "RegulatoryBody": "the regulatory body",
    "RegulatoryAction": "the regulatory action",
    "PermissibleLimit": "the permissible limit",
    "Violation": "the violation",
    "TableReference": "the table reference",
    "HealthEffect": "the health effect",
    "CausalHealthEffect": "the causal health effect",
    "AcuteEffect": "the acute effect",
    "ChronicEffect": "the chronic effect",
    "VulnerablePopulation": "the vulnerable population",
}


def type_phrase(entity_type: str) -> str:
    """Return a readable phrase for an entity type, or a generic fallback."""
    key = entity_type.replace("fflo:", "").replace("fkg:", "").replace(
        "fso:", "").replace("prov:", "").replace("lkif:", "").replace(
        "ssn:", "")
    phrase = TYPE_PHRASES.get(key)
    if phrase is None:
        return f"the {key}"
    return phrase


# ---------------------------------------------------------------------------
# Relation → sentence template  ({subj} and {obj} placeholders)
# ---------------------------------------------------------------------------

VERBALISATION_TEMPLATES: dict[str, str] = {
    # ACT
    "prov:wasAssociatedWith":     "{subj} was associated with {obj}",
    "prov:used":                  "{subj} used {obj}",
    "prov:wasGeneratedBy":        "{subj} was generated by {obj}",
    "prov:wasAttributedTo":       "{subj} was attributed to {obj}",
    "fflo:hasAdulterant":         "{subj} has the adulterant {obj}",
    "fflo:hasAdulterationMethod": "{subj} has the adulteration method {obj}",
    "fflo:hasFraudType":          "{subj} has the fraud type {obj}",
    "fflo:hasIntentionality":     "{subj} has the intentionality {obj}",
    "fflo:isSubstituteFor":       "{subj} is a substitute for {obj}",
    "fflo:commonIn":              "{subj} is common in {obj}",
    "fflo:foundAt":               "{subj} is found at {obj}",
    "fflo:hasFunction":           "{subj} functions as {obj}",
    "fkg:hasIngredient":          "{subj} contains the ingredient {obj}",
    # SPREAD
    "prov:wasInfluencedBy":       "{subj} was influenced by {obj}",
    "fflo:propagatesTo":          "{subj} propagates to {obj}",
    "fflo:carriedBy":             "{subj} is carried by {obj}",
    "fflo:occursAt":              "{subj} occurs at {obj}",
    "fflo:inputTo":               "{subj} is input to {obj}",
    "fflo:outputOf":              "{subj} is output of {obj}",
    # DETECTION
    "fso:isPerformedOn":          "{subj} is performed on {obj}",
    "fso:isPerformedAt":          "{subj} is performed at {obj}",
    "fso:isResultOf":             "{subj} is the result of {obj}",
    "fso:relatesToProperty":      "{subj} relates to the property {obj}",
    "fso:isMeasuredIn":           "{subj} is measured in {obj}",
    "fso:hasSampleType":          "{subj} has sample type {obj}",
    "fso:hasLocation":            "{subj} has location {obj}",
    "fflo:hasNumericValue":       "{subj} has a numeric value of {obj}",
    "fflo:identifies":            "{subj} identifies {obj}",
    "fflo:foundIn":               "{subj} was found in {obj}",
    "fflo:producedBy":            "{subj} was produced by {obj}",
    "fflo:confirmedBy":           "{subj} was confirmed by {obj}",
    "fflo:supportedBy":           "{subj} is supported by {obj}",
    "fflo:foundAtStep":           "{subj} was found at {obj}",
    "fflo:inRegion":              "{subj} is in the region {obj}",
    "fflo:triggeredAction":       "{subj} triggered the action {obj}",
    "fflo:collectedAt":           "{subj} was collected at {obj}",
    "fflo:detectedBy":            "{subj} is detected by {obj}",
    "fflo:producesIndicator":     "{subj} produces the indicator {obj}",
    "fflo:requiresKit":           "{subj} requires the kit {obj}",
    "fflo:isPerformedAs":         "{subj} is performed as {obj}",
    # REGULATION
    "lkif:created_by":            "{subj} was created by {obj}",
    "fflo:belongsToCategory":     "{subj} belongs to the food category {obj}",
    "fflo:appliesToCategory":     "{subj} applies to the food category {obj}",
    "fflo:hasValue":              "{subj} has a value of {obj}",
    "fflo:forProperty":           "{subj} is for the property {obj}",
    "fflo:comparedAgainst":       "{subj} is compared against {obj}",
    "fflo:definedIn":             "{subj} is defined in {obj}",
    "fflo:defines":               "{subj} defines {obj}",
    "fflo:appliesTo":             "{subj} applies to {obj}",
    "fflo:inFood":                "{subj} applies in the food {obj}",
    "fflo:hasPermissibleLimit":   "{subj} has a permissible limit of {obj}",
    "fflo:specifiedIn":           "{subj} is specified in {obj}",
    "fflo:appliesToFood":         "{subj} applies to the food {obj}",
    "fflo:compliesWith":          "{subj} complies with {obj}",
    "fflo:amends":                "{subj} amends {obj}",
    "fflo:hasSubcategory":        "{subj} has the subcategory {obj}",
    "fflo:hasDefinition":         "{subj} is defined as {obj}",
    "fflo:tableLabel":            "{subj} has the table label {obj}",
    "fflo:issuedBy":              "{subj} was issued by {obj}",
    "fflo:targets":               "{subj} targets {obj}",
    "fflo:citesFinding":          "{subj} cites the finding {obj}",
    "fflo:constitutes":           "{subj} constitutes a violation of {obj}",
    "fflo:violates":              "{subj} violates {obj}",
    # special — model explicitly gave up mapping
    "SCHEMA_MISMATCH":            "{subj} is related to {obj}",
    "fflo:appliesToCategory":     "{subj} applies to the food category {obj}",
    "fflo:hasValue":              "{subj} has a value of {obj}",
    "fflo:forProperty":           "{subj} is for the property {obj}",
    "fflo:comparedAgainst":       "{subj} is compared against {obj}",
    "fflo:definedIn":             "{subj} is defined in {obj}",
    "fflo:defines":               "{subj} defines {obj}",
    "fflo:appliesTo":             "{subj} applies to {obj}",
    "fflo:inFood":                "{subj} applies in the food {obj}",
    "fflo:hasPermissibleLimit":   "{subj} has a permissible limit of {obj}",
    "fflo:specifiedIn":           "{subj} is specified in {obj}",
    "fflo:appliesToFood":         "{subj} applies to the food {obj}",
    "fflo:compliesWith":          "{subj} complies with {obj}",
    "fflo:amends":                "{subj} amends {obj}",
    "fflo:hasSubcategory":        "{subj} has the subcategory {obj}",
    "fflo:hasDefinition":         "{subj} is defined as {obj}",
    "fflo:tableLabel":            "{subj} has the table label {obj}",
    "fflo:issuedBy":              "{subj} was issued by {obj}",
    "fflo:targets":               "{subj} targets {obj}",
    "fflo:citesFinding":          "{subj} cites the finding {obj}",
    "fflo:constitutes":           "{subj} constitutes a violation of {obj}",
    "fflo:violates":              "{subj} violates {obj}",
    # HEALTH
    "fflo:causesEffect":          "{subj} causes the health effect {obj}",
    "fflo:affectsPopulation":     "{subj} affects the population {obj}",
    "fflo:hasEffectType":         "{subj} has the effect type {obj}",
    "fflo:associatedWith":        "{subj} is associated with {obj}",
}


def verbalise(
    subject: str,
    subject_type: str,
    predicate: str,
    object_: str,
    object_type: str,
    entity_labels: dict[str, str] | None = None,
) -> str:
    """Convert a triplet into a natural-language hypothesis.

    *entity_labels* is a dict mapping entity names (or synthetic IDs) to
    descriptive labels.  Bare entity names are used when the label is
    identical to the name or when the label was auto-generated as
    ``type_phrase + name`` (in which case the template provides the
    phrasing).
    """
    if entity_labels is None:
        entity_labels = {}

    subj_label = _clean_label(subject, subject_type, entity_labels)
    obj_label = _clean_label(object_, object_type, entity_labels)

    template = VERBALISATION_TEMPLATES.get(
        predicate, "{subj} {pred} {obj}"
    )
    return template.format(subj=subj_label, pred=predicate, obj=obj_label)


def _clean_label(
    name: str,
    etype: str,
    label_map: dict[str, str],
) -> str:
    """Return the descriptive label if one was explicitly provided,
    otherwise the bare entity name.  Auto-generated labels (type_phrase
    + name) are stripped back to the bare name — the verbalisation
    template handles phrasing.
    """
    resolved = label_map.get(name)
    if resolved is None or resolved == name:
        return name
    # Check if label is just auto-generated: "the food category UnripenedCheese"
    phrase = type_phrase(etype)
    if phrase and resolved.startswith(phrase + " "):
        return name  # template handles phrasing
    return resolved
